apiVersion: operator.kyma-project.io/v1alpha1
kind: ModuleTemplate
metadata:
  name: moduletemplate-keda
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "kyma-operator"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "keda"
  annotations:
    "operator.kyma-project.io/module-version": "0.0.4"
    "operator.kyma-project.io/module-provider": "internal"
    "operator.kyma-project.io/descriptor-schema-version": "v2"
spec:
  target: remote
  channel: stable
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Keda
    metadata:
      name: keda-sample
    spec:
      foo: "testme1"  
      metricsServer:
        replicaCount: 3
      image:
        pullPolicy: "IfNotPresent"
  descriptor:
    component:
      componentReferences: []
      name: kyma.project.io/module/keda
      provider: internal
      repositoryContexts:
      - baseUrl: op-kcp-registry.localhost:50860/unsigned
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:e3af49e853889f53d2601c8fa0904daa5e88c14bec7889518d34c794172a5ae8
          type: localOciBlob
        name: keda-manager
        relation: local
        type: helm-chart
        version: 0.0.4
      sources: []
      version: 0.0.4
    meta:
      schemaVersion: v2
