apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-keda
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "keda"
spec:
  target: control-plane
  channel: fast
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Keda
    metadata:
      name: default
    spec:
      logging:
        operator:
          level: "info"
      resources:
        operator:
          limits:
            cpu: "800m"
            memory: "200Mi"
          requests:
            cpu: "300m"
            memory: "150Mi"
        metricServer:
          limits:
            cpu: "800m"
            memory: "500Mi"
          requests:
            cpu: "300m"
            memory: "500Mi"
  descriptor:
    component:
      componentReferences: []
      labels:
      - name: security.kyma-project.io/scan
        value: enabled
        version: v1
      name: kyma-project.io/module/keda
      provider: internal
      repositoryContexts:
      - baseUrl: europe-docker.pkg.dev/kyma-project/prod/unsigned
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.0.3-8e89d05
      - access:
          digest: sha256:383c2d5470efa0cd286f92abdc72d222176beefbcabcc563821190382efa2122
          type: localOciBlob
        name: raw-manifest
        relation: local
        type: yaml
        version: v0.0.3-8e89d05
      - access:
          imageReference: eu.gcr.io/kyma-project/keda-manager:v20230405-03a2ca00
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: keda-manager
        relation: external
        type: ociImage
        version: v20230405-03a2ca00
      - access:
          imageReference: ghcr.io/kedacore/keda:2.10.0
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: keda
        relation: external
        type: ociImage
        version: 2.10.0
      - access:
          imageReference: ghcr.io/kedacore/keda-admission-webhooks:2.10.0
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: keda-admission-webhooks
        relation: external
        type: ociImage
        version: 2.10.0
      - access:
          imageReference: ghcr.io/kedacore/keda-metrics-apiserver:2.10.0
          type: ociRegistry
        labels:
        - name: scan.security.kyma-project.io/type
          value: third-party-image
          version: v1
        name: keda-metrics-apiserver
        relation: external
        type: ociImage
        version: 2.10.0
      sources:
      - access:
          commit: 8e89d05eb0c2ecd492d1d099a82adc1200753100
          repoUrl: github.com/kyma-project/keda-manager
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        - name: scan.security.kyma-project.io/language
          value: golang-mod
          version: v1
        - name: scan.security.kyma-project.io/subprojects
          value: "false"
          version: v1
        - name: scan.security.kyma-project.io/exclude
          value: /test
          version: v1
        name: module-sources
        type: git
        version: v0.0.3-8e89d05
      version: v0.0.3-8e89d05
    meta:
      schemaVersion: v2