apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: keda-manager
  name: keda-manager-metrics-service
  namespace: kyma-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: keda-manager
