apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-viewer-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - configmaps/status
  - events
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - external
  - pods
  - secrets
  - serviceaccounts
  verbs:
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - "*"
  resources:
  - "*/scale"
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - "*"
- apiGroups:
  - "keda.sh"
  resources:
  - clustertriggerauthentications
  - clustertriggerauthentications/status
  - scaledjobs
  - scaledjobs/finalizers
  - scaledjobs/status
  - scaledobjects
  - scaledobjects/finalizers
  - scaledobjects/status
  - triggerauthentications
  - triggerauthentications/status
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"
---
# permissions for end users to view kedas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-viewer-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas/status
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get

