apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: operator-manager-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas/finalizers
  verbs:
  - update
- apiGroups:
  - operator.kyma-project.io
  resources:
  - kedas/status
  verbs:
  - get
  - patch
  - update
